language: cpp

sudo: required

services:
- docker

script:
 - cp -vr docker ${HOME}
 - cd ../../
 - mv -v ${TRAVIS_REPO_SLUG} $HOME/docker
 - cp -r $HOME/.ccache ${HOME}/docker/ccache
 - docker build -t espressopp/espressopp:latest ${HOME}/docker/ &&
   rm -rf $HOME/.ccache &&
   CON=$(docker run -d espressopp/espressopp:latest /bin/bash) &&
   docker cp ${CON}:/home/espressopp/.ccache ${HOME}/

after_success:
  - if [[ ${DOCKER_USERNAME} && ${DOCKER_PASSWORD} && ${TRAVIS_PULL_REQUEST} == false && ${TRAVIS_BRANCH} == docker ]]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push "espressopp/espressopp:latest";
    fi

cache:
  - ccache

compiler:
  - gcc

